"""added unique constraint to category model

Revision ID: 23972f188909
Revises: 55867a362d3e
Create Date: 2026-02-08 22:25:20.327576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23972f188909'
down_revision = '55867a362d3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_category_uc', ['name', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('_user_category_uc', type_='unique')

    # ### end Alembic commands ###
