"""add description on expenses model

Revision ID: 55867a362d3e
Revises: 5f917aecf97e
Create Date: 2026-02-08 16:56:40.928384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55867a362d3e'
down_revision = '5f917aecf97e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
