# Generated by Django 5.2.5 on 2025-08-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
