# Generated by Django 5.2.5 on 2025-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_loan_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
