# Generated by Django 5.2.5 on 2025-09-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loan_user_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='name',
            new_name='loan_name',
        ),
    ]
